# 主配置文件
# 激活环境配置
spring:
  profiles:
    active: dev
# 统一请求前缀
server:
  servlet:
    context-path: /api
  tomcat:
    max-http-header-size: 8192

# 日志配置文件（日志配置文件）
logging:
  config: classpath:log4j2.xml


# jwt相关配置
jwt:
  secret: abcdefg1234567 # 加密密钥
  expire: 6 # token有效时长（h）
  header: token # header 名称

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印将执行的sql语句
  global-config:
    db-config:
      logic-delete-field: delete_time
      logic-delete-value: now() # 逻辑已删除值
      logic-not-delete-value: 'null' # 逻辑未删除值

